<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N9F7EI8" failures="1" tests="19" name="dbp_Login_Extends.KEy_Financials" time="11.245" errors="1" timestamp="2024-06-04T18:29:42 IST" skipped="0">
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="click_on_IntrestCost" time="4.878"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Clear_Data" time="3.265"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="sendTheVAlues" time="1.403"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Save_the_Data" time="1.351">
    <failure message=" Message is Invalid expected [Saved Successfully] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  Message is Invalid expected [Saved Successfully] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at dbp_Login_Extends.KEy_Financials.Save_the_Data(KEy_Financials.java:183)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Save_the_Data -->
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Share_Capital" time="0.060">
    <error message="stale element reference: stale element not found in the current frame
  (Session info: chrome=125.0.6422.141)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: &#039;4.20.0&#039;, revision: &#039;866c76ca80&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;20.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [969c28aa3c4bc9936a5e522d4a989054, getElementAttribute {id=f.F6D05072104B489F6EF65CF7F3728F6A.d.5F3EA83A46FAC7274A887065647FC3FB.e.300, name=value}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.141, chrome: {chromedriverVersion: 125.0.6422.141 (4b1e8393712..., userDataDir: C:\Users\Thinkpad\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62351}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62351/devtoo..., se:cdpVersion: 125.0.6422.141, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (969c28aa3c4bc9936a5e522d4a989054)] -&gt; xpath: (//*[@type=&quot;text&quot;])[1]]
Session ID: 969c28aa3c4bc9936a5e522d4a989054" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found in the current frame
  (Session info: chrome=125.0.6422.141)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.20.0', revision: '866c76ca80'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [969c28aa3c4bc9936a5e522d4a989054, getElementAttribute {id=f.F6D05072104B489F6EF65CF7F3728F6A.d.5F3EA83A46FAC7274A887065647FC3FB.e.300, name=value}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 125.0.6422.141, chrome: {chromedriverVersion: 125.0.6422.141 (4b1e8393712..., userDataDir: C:\Users\Thinkpad\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62351}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62351/devtoo..., se:cdpVersion: 125.0.6422.141, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[ChromeDriver: chrome on windows (969c28aa3c4bc9936a5e522d4a989054)] -> xpath: (//*[@type="text"])[1]]
Session ID: 969c28aa3c4bc9936a5e522d4a989054
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.getAttribute(RemoteWebElement.java:149)
at dbp_Login_Extends.KEy_Financials.Share_Capital(KEy_Financials.java:193)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Share_Capital -->
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Reserves_Surplus" time="0.030"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Long_term_Debt" time="0.001"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Short_term_Debt" time="0.001"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Creditors" time="0.022"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Current_Liabilities" time="0.022"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Investment" time="0.023"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Closing_Stock" time="0.022"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Deferred_Tax_Liability" time="0.022"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Cash_in_Hand" time="0.026"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Total_Asset" time="0.022"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Debtors" time="0.025"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Current_Asset" time="0.024"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Total_Liabilities" time="0.024"/>
  <system-out/>
  <testcase classname="dbp_Login_Extends.KEy_Financials" name="Loans_Advances" time="0.024"/>
  <system-out/>
</testsuite> <!-- dbp_Login_Extends.KEy_Financials -->
