<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="1" tests="12" name="cCM_Reports.Auto_Dialer_report" time="123.110" errors="0" timestamp="2024-10-28T15:36:30 IST" skipped="0">
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Username" time="1.159"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Password" time="1.171"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Captcha" time="2.177"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="SUBMIT_Button" time="2.071"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Click_On_SMR" time="24.085"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Click_Reports" time="2.946"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Click_On_AutoDialer_REPORT" time="16.096"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="delaer_Parent_group_wise" time="18.676"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Data_Verification_Dealer_Parent_Group_Wise_Tab" time="0.037"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Data_Verification_For_Workshop_Wise_Tab" time="17.212"/>
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Data_Verification_Day_Wise_Tab" time="19.259">
    <failure message="The Day Wise report does not contain any data In Auto Dialer Report.. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The Day Wise report does not contain any data In Auto Dialer Report.. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at cCM_Reports.Auto_Dialer_report.Data_Verification_Day_Wise_Tab(Auto_Dialer_report.java:211)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Data_Verification_Day_Wise_Tab -->
  <system-out/>
  <testcase classname="cCM_Reports.Auto_Dialer_report" name="Data_Verification_SMRE_Wise_Tab" time="18.221"/>
  <system-out/>
</testsuite> <!-- cCM_Reports.Auto_Dialer_report -->
